services:
  django-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./auto_number:/auto_number
    environment:
      - DB_HOST=database
      - DB_NAME=auto_db
      - DB_USER=admin
      - DB_PASS=1234

    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=auto_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234